version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: my-mongo-db
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: my-node-app
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  mongo-data:
