version: '3.8'

services:
  flask1:
    build:
      context: .
    container_name: flask1
    networks:
      - flask_network
    expose:
      - "5000"  # Chỉ mở port trong nội bộ mạng Docker

  flask2:
    build:
      context: .
    container_name: flask2
    networks:
      - flask_network
    expose:
      - "5000"  # Chỉ mở port trong nội bộ mạng Docker

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - flask_network
    ports:
      - "8081:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount file cấu hình Nginx vào container

networks:
  flask_network:
    driver: bridge
