version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6380:6379"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
